// Code generated by qtc from "basic_search_template.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line basic_search_template.qtpl:1
package server

//line basic_search_template.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line basic_search_template.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line basic_search_template.qtpl:4
type RenderParams struct {
	SearchParams
	NodeIds         []int64
	ExcludedNodeIds []int64
}

//line basic_search_template.qtpl:11
func StreamRenderScoreSearchBody(qw422016 *qt422016.Writer, params RenderParams) {
//line basic_search_template.qtpl:11
	qw422016.N().S(`
{
    "from": `)
//line basic_search_template.qtpl:13
	qw422016.N().DL(params.From)
//line basic_search_template.qtpl:13
	qw422016.N().S(`,
    "size": `)
//line basic_search_template.qtpl:14
	qw422016.N().DL(params.Size)
//line basic_search_template.qtpl:14
	qw422016.N().S(`,
    "highlight": {
        "order": "score",
        "fragment_size": 80,
        "fields": {
            "title": {
                "number_of_fragments": 1
            },
            "content": {
                "number_of_fragments": 1
            },
            "postscript_list.content": {
                "number_of_fragments": 1
            },
            "reply_list.content": {
                "number_of_fragments": 1,
                "highlight_query": {
                    "nested": {
                        "path": "reply_list",
                        "query": {
                            "match": {
                                "reply_list.content": {
                                    "query": "`)
//line basic_search_template.qtpl:36
	qw422016.N().S(params.Keyword)
//line basic_search_template.qtpl:36
	qw422016.N().S(`",
                                    "analyzer": "ik_smart"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "_source": ["title",
                "content",
                "created",
                "id",
                "node",
                "replies",
                "member"],
    "query": {
        "function_score": {
            "query": {
                "bool": {
                    "must": `)
//line basic_search_template.qtpl:57
	streammustQuery(qw422016, params)
//line basic_search_template.qtpl:57
	qw422016.N().S(`,
                    "must_not": `)
//line basic_search_template.qtpl:58
	streammustNotQuery(qw422016, params)
//line basic_search_template.qtpl:58
	qw422016.N().S(`,
                    "minimum_should_match": 1,
                    "should": [
                        {
                            "match": {
                                "title": {
                                    "query": "`)
//line basic_search_template.qtpl:64
	qw422016.N().S(params.Keyword)
//line basic_search_template.qtpl:64
	qw422016.N().S(`",
                                    "analyzer": "ik_smart",
                                    "boost": 3,
                                    "operator": "`)
//line basic_search_template.qtpl:67
	qw422016.N().S(params.Operator)
//line basic_search_template.qtpl:67
	qw422016.N().S(`"
                                }
                            }
                        },
                        {
                            "bool": {
                                "should": [
                                    {
                                        "match": {
                                            "content": {
                                                "query": "`)
//line basic_search_template.qtpl:77
	qw422016.N().S(params.Keyword)
//line basic_search_template.qtpl:77
	qw422016.N().S(`",
                                                "analyzer": "ik_smart",
                                                "boost": 2,
                                                "operator": "`)
//line basic_search_template.qtpl:80
	qw422016.N().S(params.Operator)
//line basic_search_template.qtpl:80
	qw422016.N().S(`"
                                            }
                                        }
                                    },
                                    {
                                        "nested": {
                                            "path": "postscript_list",
                                            "score_mode": "max",
                                            "query": {
                                                "match": {
                                                    "postscript_list.content": {
                                                        "query": "`)
//line basic_search_template.qtpl:91
	qw422016.N().S(params.Keyword)
//line basic_search_template.qtpl:91
	qw422016.N().S(`",
                                                        "analyzer": "ik_smart",
                                                        "boost": 2,
                                                        "operator": "`)
//line basic_search_template.qtpl:94
	qw422016.N().S(params.Operator)
//line basic_search_template.qtpl:94
	qw422016.N().S(`"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            "match": {
                                "all_reply": {
                                    "query": "`)
//line basic_search_template.qtpl:106
	qw422016.N().S(params.Keyword)
//line basic_search_template.qtpl:106
	qw422016.N().S(`",
                                    "analyzer": "ik_smart",
                                    "boost": 1.5,
                                    "operator": "`)
//line basic_search_template.qtpl:109
	qw422016.N().S(params.Operator)
//line basic_search_template.qtpl:109
	qw422016.N().S(`"
                                }
                            }
                        }
                    ]
                }
            },
            "functions": [
                {
                    "filter": {"match_phrase": {
                        "all_content": {
                            "query": "`)
//line basic_search_template.qtpl:120
	qw422016.N().S(params.Keyword)
//line basic_search_template.qtpl:120
	qw422016.N().S(`",
                            "analyzer": "ik_max_word",
                            "slop": 0
                        }
                    }},
                    "weight": 50
                },
                {
                    "field_value_factor": {
                        "field": "bonus",
                        "missing": 0,
                        "modifier": "none",
                        "factor": 1
                    }
                }
            ],
            "score_mode": "sum",
            "boost_mode": "sum"
        }
    }
}
`)
//line basic_search_template.qtpl:141
}

//line basic_search_template.qtpl:141
func WriteRenderScoreSearchBody(qq422016 qtio422016.Writer, params RenderParams) {
//line basic_search_template.qtpl:141
	qw422016 := qt422016.AcquireWriter(qq422016)
//line basic_search_template.qtpl:141
	StreamRenderScoreSearchBody(qw422016, params)
//line basic_search_template.qtpl:141
	qt422016.ReleaseWriter(qw422016)
//line basic_search_template.qtpl:141
}

//line basic_search_template.qtpl:141
func RenderScoreSearchBody(params RenderParams) string {
//line basic_search_template.qtpl:141
	qb422016 := qt422016.AcquireByteBuffer()
//line basic_search_template.qtpl:141
	WriteRenderScoreSearchBody(qb422016, params)
//line basic_search_template.qtpl:141
	qs422016 := string(qb422016.B)
//line basic_search_template.qtpl:141
	qt422016.ReleaseByteBuffer(qb422016)
//line basic_search_template.qtpl:141
	return qs422016
//line basic_search_template.qtpl:141
}

//line basic_search_template.qtpl:144
func StreamRenderTimeOrderSearchBody(qw422016 *qt422016.Writer, params RenderParams) {
//line basic_search_template.qtpl:144
	qw422016.N().S(`
{
    "from": `)
//line basic_search_template.qtpl:146
	qw422016.N().DL(params.From)
//line basic_search_template.qtpl:146
	qw422016.N().S(`,
    "size": `)
//line basic_search_template.qtpl:147
	qw422016.N().DL(params.Size)
//line basic_search_template.qtpl:147
	qw422016.N().S(`,
    "sort": [
        {
            "created": {
                "order":
                `)
//line basic_search_template.qtpl:152
	if params.Order == 1 {
//line basic_search_template.qtpl:152
		qw422016.N().S(`
                "asc"
                `)
//line basic_search_template.qtpl:154
	} else {
//line basic_search_template.qtpl:154
		qw422016.N().S(`
                "desc"
                `)
//line basic_search_template.qtpl:156
	}
//line basic_search_template.qtpl:156
	qw422016.N().S(`
            }
        }
    ],
    "highlight": {
        "order": "score",
        "fragment_size": 80,
        "fields": {
            "title": {
                "number_of_fragments": 1
            },
            "content": {
                "number_of_fragments": 1
            },
            "postscript_list.content": {
                "number_of_fragments": 1
            },
            "reply_list.content": {
                "number_of_fragments": 1,
                "highlight_query": {
                    "nested": {
                        "path": "reply_list",
                        "query": {
                            "match": {
                                "reply_list.content": {
                                    "query": "`)
//line basic_search_template.qtpl:181
	qw422016.N().S(params.Keyword)
//line basic_search_template.qtpl:181
	qw422016.N().S(`",
                                    "analyzer": "ik_smart"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "_source": [
        "title",
        "content",
        "created",
        "id",
        "node",
        "replies",
        "member"
    ],
    "query": {
        "constant_score": {
            "filter": {
                "bool": {
                    "must": `)
//line basic_search_template.qtpl:204
	streammustQuery(qw422016, params)
//line basic_search_template.qtpl:204
	qw422016.N().S(`,
                    "must_not": `)
//line basic_search_template.qtpl:205
	streammustNotQuery(qw422016, params)
//line basic_search_template.qtpl:205
	qw422016.N().S(`,
                    "minimum_should_match": 1,
                    "should": [
                        {
                            "match": {
                                "title": {
                                    "query": "`)
//line basic_search_template.qtpl:211
	qw422016.N().S(params.Keyword)
//line basic_search_template.qtpl:211
	qw422016.N().S(`",
                                    "analyzer": "ik_smart",
                                    "minimum_should_match": "2<70%",
                                    "operator": "`)
//line basic_search_template.qtpl:214
	qw422016.N().S(params.Operator)
//line basic_search_template.qtpl:214
	qw422016.N().S(`"
                                }
                            }
                        },
                        {
                            "match": {
                                "content": {
                                    "query": "`)
//line basic_search_template.qtpl:221
	qw422016.N().S(params.Keyword)
//line basic_search_template.qtpl:221
	qw422016.N().S(`",
                                    "analyzer": "ik_smart",
                                    "minimum_should_match": "2<70%",
                                    "operator": "`)
//line basic_search_template.qtpl:224
	qw422016.N().S(params.Operator)
//line basic_search_template.qtpl:224
	qw422016.N().S(`"
                                }
                            }
                        },
                        {
                            "nested": {
                                "path": "postscript_list",
                                "score_mode": "max",
                                "query": {
                                    "match": {
                                        "postscript_list.content": {
                                            "query": "`)
//line basic_search_template.qtpl:235
	qw422016.N().S(params.Keyword)
//line basic_search_template.qtpl:235
	qw422016.N().S(`",
                                            "analyzer": "ik_smart",
                                            "minimum_should_match": "2<70%",
                                            "operator": "`)
//line basic_search_template.qtpl:238
	qw422016.N().S(params.Operator)
//line basic_search_template.qtpl:238
	qw422016.N().S(`"
                                        }
                                    }
                                }
                            }
                        },
                        {
                            "match_phrase": {
                                "all_reply": {
                                    "query": "`)
//line basic_search_template.qtpl:247
	qw422016.N().S(params.Keyword)
//line basic_search_template.qtpl:247
	qw422016.N().S(`",
                                    "analyzer": "ik_max_word",
                                    "slop": 0
                                }
                            }
                        }
                    ]
                }
            }
        }
    }
}
`)
//line basic_search_template.qtpl:259
}

//line basic_search_template.qtpl:259
func WriteRenderTimeOrderSearchBody(qq422016 qtio422016.Writer, params RenderParams) {
//line basic_search_template.qtpl:259
	qw422016 := qt422016.AcquireWriter(qq422016)
//line basic_search_template.qtpl:259
	StreamRenderTimeOrderSearchBody(qw422016, params)
//line basic_search_template.qtpl:259
	qt422016.ReleaseWriter(qw422016)
//line basic_search_template.qtpl:259
}

//line basic_search_template.qtpl:259
func RenderTimeOrderSearchBody(params RenderParams) string {
//line basic_search_template.qtpl:259
	qb422016 := qt422016.AcquireByteBuffer()
//line basic_search_template.qtpl:259
	WriteRenderTimeOrderSearchBody(qb422016, params)
//line basic_search_template.qtpl:259
	qs422016 := string(qb422016.B)
//line basic_search_template.qtpl:259
	qt422016.ReleaseByteBuffer(qb422016)
//line basic_search_template.qtpl:259
	return qs422016
//line basic_search_template.qtpl:259
}

//line basic_search_template.qtpl:261
func streammustQuery(qw422016 *qt422016.Writer, params RenderParams) {
//line basic_search_template.qtpl:261
	qw422016.N().S(`
    `)
//line basic_search_template.qtpl:262
	needComma := false

//line basic_search_template.qtpl:262
	qw422016.N().S(`
    [
        `)
//line basic_search_template.qtpl:264
	if params.Gte > 0 || params.Lte > 0 {
//line basic_search_template.qtpl:264
		qw422016.N().S(`
        `)
//line basic_search_template.qtpl:265
		needComma = true

//line basic_search_template.qtpl:265
		qw422016.N().S(`
        {
          "range": {
            "created": {
              `)
//line basic_search_template.qtpl:269
		if params.Gte > 0 {
//line basic_search_template.qtpl:269
			qw422016.N().S(`"gte": `)
//line basic_search_template.qtpl:269
			qw422016.N().DL(params.Gte)
//line basic_search_template.qtpl:269
			qw422016.N().S(`,`)
//line basic_search_template.qtpl:269
		}
//line basic_search_template.qtpl:269
		qw422016.N().S(`
              `)
//line basic_search_template.qtpl:270
		if params.Lte > 0 {
//line basic_search_template.qtpl:270
			qw422016.N().S(`"lte": `)
//line basic_search_template.qtpl:270
			qw422016.N().DL(params.Lte)
//line basic_search_template.qtpl:270
			qw422016.N().S(`,`)
//line basic_search_template.qtpl:270
		}
//line basic_search_template.qtpl:270
		qw422016.N().S(`
              "format": "epoch_second"
            }
          }
        }
        `)
//line basic_search_template.qtpl:275
	}
//line basic_search_template.qtpl:275
	qw422016.N().S(`

        `)
//line basic_search_template.qtpl:277
	if len(params.NodeIds) > 0 {
//line basic_search_template.qtpl:277
		qw422016.N().S(`
        `)
//line basic_search_template.qtpl:278
		if needComma {
//line basic_search_template.qtpl:278
			qw422016.N().S(`,`)
//line basic_search_template.qtpl:278
		}
//line basic_search_template.qtpl:278
		qw422016.N().S(`
        `)
//line basic_search_template.qtpl:279
		needComma = true

//line basic_search_template.qtpl:279
		qw422016.N().S(`
        {
            "terms": {
                "node":[
                    `)
//line basic_search_template.qtpl:283
		for i, id := range params.NodeIds {
//line basic_search_template.qtpl:283
			qw422016.N().S(`
                        `)
//line basic_search_template.qtpl:284
			if i != 0 {
//line basic_search_template.qtpl:284
				qw422016.N().S(`
                            ,
                        `)
//line basic_search_template.qtpl:286
			}
//line basic_search_template.qtpl:286
			qw422016.N().S(`
                        `)
//line basic_search_template.qtpl:287
			qw422016.N().DL(id)
//line basic_search_template.qtpl:287
			qw422016.N().S(`
                    `)
//line basic_search_template.qtpl:288
		}
//line basic_search_template.qtpl:288
		qw422016.N().S(`
                ]
            }
        }
        `)
//line basic_search_template.qtpl:292
	}
//line basic_search_template.qtpl:292
	qw422016.N().S(`

        `)
//line basic_search_template.qtpl:294
	if params.Username != "" {
//line basic_search_template.qtpl:294
		qw422016.N().S(`
        `)
//line basic_search_template.qtpl:295
		if needComma {
//line basic_search_template.qtpl:295
			qw422016.N().S(`,`)
//line basic_search_template.qtpl:295
		}
//line basic_search_template.qtpl:295
		qw422016.N().S(`
        `)
//line basic_search_template.qtpl:296
		needComma = true

//line basic_search_template.qtpl:296
		qw422016.N().S(`
            {
                "term": {
                    "member": {
                        "value": "`)
//line basic_search_template.qtpl:300
		qw422016.N().S(params.Username)
//line basic_search_template.qtpl:300
		qw422016.N().S(`"
                    }
                }
            }
        `)
//line basic_search_template.qtpl:304
	}
//line basic_search_template.qtpl:304
	qw422016.N().S(`
    ]
`)
//line basic_search_template.qtpl:306
}

//line basic_search_template.qtpl:306
func writemustQuery(qq422016 qtio422016.Writer, params RenderParams) {
//line basic_search_template.qtpl:306
	qw422016 := qt422016.AcquireWriter(qq422016)
//line basic_search_template.qtpl:306
	streammustQuery(qw422016, params)
//line basic_search_template.qtpl:306
	qt422016.ReleaseWriter(qw422016)
//line basic_search_template.qtpl:306
}

//line basic_search_template.qtpl:306
func mustQuery(params RenderParams) string {
//line basic_search_template.qtpl:306
	qb422016 := qt422016.AcquireByteBuffer()
//line basic_search_template.qtpl:306
	writemustQuery(qb422016, params)
//line basic_search_template.qtpl:306
	qs422016 := string(qb422016.B)
//line basic_search_template.qtpl:306
	qt422016.ReleaseByteBuffer(qb422016)
//line basic_search_template.qtpl:306
	return qs422016
//line basic_search_template.qtpl:306
}

//line basic_search_template.qtpl:308
func streammustNotQuery(qw422016 *qt422016.Writer, params RenderParams) {
//line basic_search_template.qtpl:308
	qw422016.N().S(`
    [
        {
            "term": {
                "deleted": true
            }
        }
        `)
//line basic_search_template.qtpl:315
	if len(params.ExcludedNodeIds) > 0 {
//line basic_search_template.qtpl:315
		qw422016.N().S(`
            ,
            {
                "terms": {
                    "node":[
                        `)
//line basic_search_template.qtpl:320
		for i, id := range params.ExcludedNodeIds {
//line basic_search_template.qtpl:320
			qw422016.N().S(`
                            `)
//line basic_search_template.qtpl:321
			if i != 0 {
//line basic_search_template.qtpl:321
				qw422016.N().S(`
                                ,
                            `)
//line basic_search_template.qtpl:323
			}
//line basic_search_template.qtpl:323
			qw422016.N().S(`
                            `)
//line basic_search_template.qtpl:324
			qw422016.N().DL(id)
//line basic_search_template.qtpl:324
			qw422016.N().S(`
                        `)
//line basic_search_template.qtpl:325
		}
//line basic_search_template.qtpl:325
		qw422016.N().S(`
                    ]
                }
            }
        `)
//line basic_search_template.qtpl:329
	}
//line basic_search_template.qtpl:329
	qw422016.N().S(`
    ]
`)
//line basic_search_template.qtpl:331
}

//line basic_search_template.qtpl:331
func writemustNotQuery(qq422016 qtio422016.Writer, params RenderParams) {
//line basic_search_template.qtpl:331
	qw422016 := qt422016.AcquireWriter(qq422016)
//line basic_search_template.qtpl:331
	streammustNotQuery(qw422016, params)
//line basic_search_template.qtpl:331
	qt422016.ReleaseWriter(qw422016)
//line basic_search_template.qtpl:331
}

//line basic_search_template.qtpl:331
func mustNotQuery(params RenderParams) string {
//line basic_search_template.qtpl:331
	qb422016 := qt422016.AcquireByteBuffer()
//line basic_search_template.qtpl:331
	writemustNotQuery(qb422016, params)
//line basic_search_template.qtpl:331
	qs422016 := string(qb422016.B)
//line basic_search_template.qtpl:331
	qt422016.ReleaseByteBuffer(qb422016)
//line basic_search_template.qtpl:331
	return qs422016
//line basic_search_template.qtpl:331
}
